# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 09:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('[aA-zZ]+(?:[aA-zZ]+) [aA-zZ]+\\Z', code='invalid', message='Enter a valid name (first & last, letters only).')], verbose_name='Full Name'),
        ),
    ]
