# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('landing', '0003_service'), ('landing', '0004_service_html'), ('landing', '0005_service_order'), ('landing', '0006_auto_20160910_2337'), ('landing', '0007_auto_20160910_2337'), ('landing', '0008_auto_20160911_0003')]

    dependencies = [
        ('landing', '0002_auto_20160823_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Service Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('html', models.TextField(default=django.utils.timezone.now, verbose_name='HTML Markup')),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
    ]
