# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_service_squashed_0008_auto_20160911_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='html',
            field=models.TextField(verbose_name='HTML Markup'),
        ),
    ]
