# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_service_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
