# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20160911_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order',)},
        ),
    ]
