# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20160910_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
