# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20160916_0318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
