# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='anchor_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anchor ID'),
        ),
    ]
