# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_service_anchor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='anchor_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='html',
        ),
    ]
