# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20161015_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
