# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20161015_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
