# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_service_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'get_latest_by': 'modified', 'ordering': ('order',)},
        ),
    ]
