# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.ManyToManyField(to='metadata.Keyword', verbose_name='keywords')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.LocalBusiness')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=500, verbose_name='url'),
        ),
    ]
