# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20160927_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localbusiness',
            options={'verbose_name_plural': 'Local Businesses'},
        ),
        migrations.AlterModelOptions(
            name='postaladdress',
            options={'verbose_name_plural': 'Postal Addresses'},
        ),
    ]
