# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_link_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, to='metadata.Tag'),
        ),
    ]
