# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_auto_20160927_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='postaladdress',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='postaladdress',
            name='region',
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='kind',
            field=models.CharField(choices=[('MA', 'Main'), ('HO', 'Home'), ('CE', 'Cell'), ('WO', 'Work'), ('FX', 'Fax'), ('OT', 'Other')], default='MA', max_length=2, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.State', verbose_name='addressRegion'),
        ),
    ]
