# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20160928_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaladdress',
            name='locality',
            field=models.CharField(default='Plano', max_length=200, verbose_name='addressLocality'),
            preserve_default=False,
        ),
    ]
